version: '3.8'

services:
  green:
    build:
      context: ./app
    environment:
      - VERSION=green
    networks:
      - web
    container_name: app_green

  blue:
    build:
      context: ./app
    environment:
      - VERSION=blue
    networks:
      - web
    container_name: app_blue

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - web
    environment:
      TARGET: blue 
    depends_on:
      - green
      - blue

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - web

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - web

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    networks:
      - web

networks:
  web:
